### ISSUE TITLE
"Protocol not available" error over https

### ISSUE THREAD

**Issue by danielkrizian** [jonathonmcmurray/reQ#18]
First off, thanks so much for the reQ package!

I tried to follow your [blog article](https://jmcmurray.co.uk/kdb/q/package/qutil/anaconda/conda/2018/07/16/q-package-management-with-conda.html) and get this error when trying https protocol. http works fine. 

```q
q).utl.require"req"
q).req.g"https://httpbin.org/get"
'conn. OS reports: Protocol not available
  [2]  /opt/miniconda3/envs/build/q/pkg/req/req.q:164: .req.send:
  d:headers[us;pr;hd;p];                                                            //get dictionary of HTTP headers for request
  r:hs d:buildquery[m;pr;nu;h;d;p];                                                 //build query and execute
    ^
  if[v;-1"-- REQUEST --\n",string[hs],"\n",d];                                      //if verbose, log request
q.req))
q).req.g"http://httpbin.org/get"
args   | (`symbol$())!()
headers| `Accept`Connection`Host`User-Agent!("*/*";"close";"httpbin.org";"kdb..
origin | "208.110.70.170"
url    | "http://httpbin.org/get"
```

I think I installed all dependencies:
```shell
(build) [dk@s110519 /home/dk/conda-pkgs]$ conda list
# packages in environment at /opt/miniconda3/envs/build:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0  
json                      0.1.1                         0    file://opt/channel
q                         3.6                           0    file://opt/channel
qhttps                    0.0.1                         0    local
qlic                      2018.11.25                    0    file://opt/channel
qutil                     3.2.1                         0    file://opt/channel
req                       0.1.2                         0    file://opt/channel
```

**Comment by jonathonmcmurray** [comment]
Hi

Apologies for delayed response. This looks like it could be an issue with OpenSSL; kdb+ requires version 1.0.* of OpenSSL and conda may have installed version 1.1.*

You can check like so:

```
jonny@kodiak ~ $ openssl version
OpenSSL 1.1.1a  20 Nov 2018
```

In this case, you would need to downgrade your OpenSSL in your conda env like so:

```
$ conda install openssl=1.0.*
```

Within q, you can check your OpenSSL configuration with `-26!()`, which should give an error with wrong version of OpenSSL, or something like this is correctly configured:

```q
q)-26!()
SSLEAY_VERSION   | OpenSSL 1.0.2g  1 Mar 2016
SSL_CERT_FILE    | /usr/lib/ssl/server-crt.pem
SSL_CA_CERT_FILE | /opt/kdb/cabundle.pem
SSL_CA_CERT_PATH | /usr/lib/ssl
SSL_KEY_FILE     | /usr/lib/ssl/server-key.pem
SSL_CIPHER_LIST  | ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:..
SSL_VERIFY_CLIENT| NO
SSL_VERIFY_SERVER| YES
```

Once OpenSSL is configured properly, HTTPS should work in reQ with your example above.

Hope that helps!

**Comment by danielkrizian** [comment]
Thanks for pointers! I also ran diagnostics as suggested by [Charles on k4 Topicbox](https://k4.topicbox.com/groups/k4/T7f1230528ba7f79d-M1c8948f1dd286e7834d74b85/could-not-initialize-openssl-error-was-incompatible-ssl-version) and found that I had this line in my `.bashrc`:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/miniconda3/lib`.

Removing it and `conda install openssl=1.0.*` indeed fixed the issue. 
I learnt that it's best not to hardcode the LD_LIBRARY_PATH, but let conda manage the dependencies.
Many thanks!
